// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketSnapshotMessageSpec.proto

package org.openfeed.proto.data;

public final class MarketSnapshotMessageSpec {
  private MarketSnapshotMessageSpec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_openfeed_proto_data_MarketSnapshotMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_openfeed_proto_data_MarketSnapshotMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037MarketSnapshotMessageSpec.proto\022\027org.o" +
      "penfeed.proto.data\032\025MarketEntrySpec.prot" +
      "o\"\375\001\n\025MarketSnapshotMessage\022\020\n\010marketId\030" +
      "\001 \001(\022\022\020\n\010sequence\030\002 \001(\022\022\032\n\022lastUpdateSeq" +
      "uence\030\003 \001(\022\022\021\n\ttimeStamp\030\004 \001(\022\022\021\n\ttradeD" +
      "ate\030\005 \001(\021\0223\n\005entry\030\006 \003(\0132$.org.openfeed." +
      "proto.data.MarketEntry\022\025\n\rpriceExponent\030" +
      "\007 \001(\021\022\024\n\014sizeExponent\030\010 \001(\021\022\034\n\024totalExpe" +
      "ctedEntries\030\t \001(\021B\007H\001P\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_openfeed_proto_data_MarketSnapshotMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_openfeed_proto_data_MarketSnapshotMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_openfeed_proto_data_MarketSnapshotMessage_descriptor,
              new java.lang.String[] { "MarketId", "Sequence", "LastUpdateSequence", "TimeStamp", "TradeDate", "Entry", "PriceExponent", "SizeExponent", "TotalExpectedEntries", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.openfeed.proto.data.MarketEntrySpec.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
