// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketSnapshotPacketSpec.proto

package org.openfeed.proto.data;

public final class MarketSnapshotPacketSpec {
  private MarketSnapshotPacketSpec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_openfeed_proto_data_MarketSnapshotPacket_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_openfeed_proto_data_MarketSnapshotPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036MarketSnapshotPacketSpec.proto\022\027org.op" +
      "enfeed.proto.data\032\032MarketPacketTypeSpec." +
      "proto\032\037MarketSnapshotMessageSpec.proto\"\321" +
      "\001\n\024MarketSnapshotPacket\022\017\n\007channel\030\001 \001(\021" +
      "\022\020\n\010sequence\030\002 \001(\022\022\021\n\ttimeStamp\030\003 \001(\022\022B\n" +
      "\004type\030\004 \001(\0162#.org.openfeed.proto.data.Pa" +
      "cketType:\017MARKET_SNAPSHOT\022?\n\007message\030\005 \003" +
      "(\0132..org.openfeed.proto.data.MarketSnaps" +
      "hotMessageB\007H\001P\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_openfeed_proto_data_MarketSnapshotPacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_openfeed_proto_data_MarketSnapshotPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_openfeed_proto_data_MarketSnapshotPacket_descriptor,
              new java.lang.String[] { "Channel", "Sequence", "TimeStamp", "Type", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.openfeed.proto.data.MarketPacketTypeSpec.getDescriptor(),
          org.openfeed.proto.data.MarketSnapshotMessageSpec.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
