// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketPacketTypeSpec.proto

package org.openfeed.proto.data;

public final class MarketPacketTypeSpec {
  private MarketPacketTypeSpec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032MarketPacketTypeSpec.proto\022\027org.openfe" +
      "ed.proto.data*A\n\nPacketType\022\013\n\007UNKNOWN\020\000" +
      "\022\021\n\rMARKET_UPDATE\020\001\022\023\n\017MARKET_SNAPSHOT\020\002" +
      "B\007H\001P\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
