// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketEntrySpec.proto

package org.openfeed.proto.data;

public final class MarketEntrySpec {
  private MarketEntrySpec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_openfeed_proto_data_MarketEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_openfeed_proto_data_MarketEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MarketEntrySpec.proto\022\027org.openfeed.pr" +
      "oto.data\"\234\017\n\013MarketEntry\022;\n\006action\030\001 \001(\016" +
      "2+.org.openfeed.proto.data.MarketEntry.A" +
      "ction\0227\n\004type\030\002 \001(\0162).org.openfeed.proto" +
      ".data.MarketEntry.Type\022G\n\ndescriptor\030\003 \003" +
      "(\0162/.org.openfeed.proto.data.MarketEntry" +
      ".DescriptorB\002\020\001\022\020\n\010marketId\030\004 \001(\022\022\020\n\010seq" +
      "uence\030\005 \001(\022\022\021\n\ttimeStamp\030\006 \001(\022\022\021\n\ttradeD" +
      "ate\030\007 \001(\021\022\025\n\rpriceMantissa\030\010 \001(\022\022\025\n\rpric" +
      "eExponent\030\t \001(\021\022\024\n\014sizeMantissa\030\n \001(\022\022\024\n",
      "\014sizeExponent\030\013 \001(\021\022\r\n\005index\030\014 \001(\022\022\017\n\007or" +
      "derId\030\r \001(\022\022\022\n\norderCount\030\016 \001(\021\"\'\n\006Actio" +
      "n\022\007\n\003ADD\020\000\022\010\n\004EDIT\020\001\022\n\n\006REMOVE\020\002\"\311\001\n\004Typ" +
      "e\022\t\n\005TRADE\020\000\022\007\n\003BID\020\001\022\007\n\003ASK\020\002\022\n\n\006CHANGE" +
      "\020\003\022\016\n\nUNDERLYING\020\004\022\n\n\006VOLUME\020\005\022\010\n\004OPEN\020\006" +
      "\022\010\n\004HIGH\020\007\022\007\n\003LOW\020\010\022\t\n\005CLOSE\020\t\022\n\n\006SETTLE" +
      "\020\n\022\014\n\010INTEREST\020\013\022\t\n\005CUVOL\020\014\022\n\n\006STATUS\020\r\022" +
      "\014\n\010SEQUENCE\020\016\022\010\n\004TIME\020~\022\013\n\007UNKNOWN\020\177\"\200\n\n" +
      "\nDescriptor\022\020\n\014BOOK_IMPLIED\020\000\022\014\n\010BOOK_RF" +
      "Q\020\001\022\025\n\021SETTLE_UNOFFICIAL\020\002\022\026\n\022SETTLE_PRE",
      "LIMINARY\020\003\022\026\n\022SETTLE_THEORETICAL\020\004\022\016\n\nPE" +
      "RIOD_DAY\020\n\022\017\n\013PERIOD_WEEK\020\013\022\020\n\014PERIOD_MO" +
      "NTH\020\014\022\017\n\013PERIOD_YEAR\020\r\022\r\n\tLAST_BEST\020\016\022\020\n" +
      "\014SESSION_HIGH\020\024\022\017\n\013SESSION_LOW\020\025\022\022\n\016ADJU" +
      "STED_TRADE\020\036\022\025\n\021SESSION_OVERNIGHT\0202\022\017\n\013O" +
      "RDER_COUNT\020<\022\024\n\020IMPLIED_QUANTITY\020=\022\027\n\023IM" +
      "PLIED_ORDER_COUNT\020>\022\032\n\026NUMBER_OF_BOOK_EN" +
      "TRIES\020F\022\031\n\025LAST_MESSAGE_SEQUENCE\020G\022\016\n\nPE" +
      "RCENTAGE\020H\022\024\n\020OVER_THE_COUNTER\020I\022\023\n\017EXCH" +
      "ANGE_TRADED\020J\022\032\n\026OPTION_THEORETICAL_BID\020",
      "P\022\032\n\026OPTION_THEORETICAL_ASK\020Q\022\020\n\014OPTION_" +
      "DELTA\020R\022\017\n\013OPTION_VEGA\020S\022\026\n\022STATUS_MARKE" +
      "T_OPEN\020d\022\027\n\023STATUS_MARKET_CLOSE\020e\022\032\n\026STA" +
      "TUS_MARKET_PRE_OPEN\020f\022\033\n\027STATUS_MARKET_P" +
      "RE_CLOSE\020g\022\030\n\024STATUS_TRADING_PAUSE\020h\022\031\n\025" +
      "STATUS_TRADING_RESUME\020i\022\031\n\025STATUS_MARKET" +
      "_EXPIRED\020j\022\r\n\tSIDE_FIRM\020n\022\021\n\rSIDE_CUSTOM" +
      "ER\020o\022\022\n\016INDEX_ON_TRADE\020p\022\021\n\rINDEX_ON_BOO" +
      "K\020q\022\020\n\014VOLUME_BLOCK\020x\022\016\n\nVOLUME_EFS\020y\022\016\n" +
      "\nVOLUME_EFP\020z\022\016\n\nPRICE_VWAP\020{\022\020\n\014PRICE_S",
      "YSTEM\020|\022\017\n\013TRADE_BLOCK\020}\022\022\n\016TRADE_CANCEL" +
      "ED\020~\022\026\n\022TRADE_INVESTIGATED\020\177\022\r\n\010PRE_OPEN" +
      "\020\264\001\022\022\n\rOPEN_INTEREST\020\265\001\022\020\n\013BLOCK_TRADE\020\310" +
      "\001\022\016\n\tEFP_TRADE\020\311\001\022\016\n\tEFS_TRADE\020\312\001\022!\n\034BIL" +
      "ATERAL_OFF_EXCHANGE_TRADE\020\313\001\022\025\n\020NG_EFP_E" +
      "FS_TRADE\020\314\001\022\022\n\rCCX_EFP_TRADE\020\315\001\022\016\n\tEFR_T" +
      "RADE\020\316\001\022#\n\036SYSTEM_PRICED_CRACK_SPREAD_LE" +
      "G\020\317\001\022\026\n\021SYSTEM_PRICED_LEG\020\320\001\022\"\n\035IMPLIED_" +
      "SPREAD_AT_MARKET_OPEN\020\321\001\022\020\n\013TIME_OPENED\020" +
      "\372\001\022\020\n\013TIME_CLOSED\020\373\001\022\021\n\014TIME_UPDATED\020\374\001B",
      "\007H\001P\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_openfeed_proto_data_MarketEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_openfeed_proto_data_MarketEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_openfeed_proto_data_MarketEntry_descriptor,
              new java.lang.String[] { "Action", "Type", "Descriptor", "MarketId", "Sequence", "TimeStamp", "TradeDate", "PriceMantissa", "PriceExponent", "SizeMantissa", "SizeExponent", "Index", "OrderId", "OrderCount", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
