// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketUpdateMessageSpec.proto

package org.openfeed.proto.data;

public final class MarketUpdateMessageSpec {
  private MarketUpdateMessageSpec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_openfeed_proto_data_MarketUpdateMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_openfeed_proto_data_MarketUpdateMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035MarketUpdateMessageSpec.proto\022\027org.ope" +
      "nfeed.proto.data\032\025MarketEntrySpec.proto\"" +
      "\301\001\n\023MarketUpdateMessage\022\020\n\010marketId\030\001 \001(" +
      "\022\022\020\n\010sequence\030\002 \001(\022\022\021\n\ttimeStamp\030\003 \001(\022\022\021" +
      "\n\ttradeDate\030\004 \001(\021\022\025\n\rpriceExponent\030\005 \001(\021" +
      "\022\024\n\014sizeExponent\030\006 \001(\021\0223\n\005entry\030\007 \003(\0132$." +
      "org.openfeed.proto.data.MarketEntryB\007H\001P" +
      "\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_openfeed_proto_data_MarketUpdateMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_openfeed_proto_data_MarketUpdateMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_openfeed_proto_data_MarketUpdateMessage_descriptor,
              new java.lang.String[] { "MarketId", "Sequence", "TimeStamp", "TradeDate", "PriceExponent", "SizeExponent", "Entry", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.openfeed.proto.data.MarketEntrySpec.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
